/* global module */
module.exports = {
  'base': '{protocol}://{hostname}/u/{username}/p/{reponame}',
  'home': '/git',
  'issues': '/topic',
  'issues/id': '/topic/{issue-id}',
  'issues/new': '/topic/new',
  'issues/new?title': '/topic/new?title={title}',
  'wiki': '/wiki',
  'network': '/git/graph',
  'tree': '/git/tree/{hash}',
  'blob': '/git/blob/{hash}',
  'commits': '/git/commits',
  'commits-with-branch': '/git/commits/{branch-name}',
  'milestones': '/milestones',
  'tags': '/git/tags',
  'releases': '/git/releases',
  'releases/new': '/git/releases/new',
  'releases/new-with-tag': '/git/releases/new?tag={tag}',
  'releases/edit/tag-id': '/git/releases/edit/{tag}',
  'pulls': '/git/pulls',
  'pulls/new': '/git/compare',
  'pulls/new-with-branch': '/git/compare/{branch-A}...{branch-B}',
};
